### PR TITLE
Updating .travis.yml

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR begins the updating process of `.travis.yml` and will end with the introduction of `python 3.7` support (and dropping support for `python 3.5`).

### CODE REVIEW

**Comment by jGaboardi** [comment]
@sjsrey the Travis CI {3.5,3.6} --> {3.6,3.7} testing bump passes without incident.

**Comment by jGaboardi** [comment]
related to #9

**Review by weikang9009 — APPROVED** [review]

**Comment by jGaboardi** [comment]
#11

**Review by sjsrey — APPROVED** [review]

**Comment by jGaboardi** [comment]
Closing per #18

**Pull request closed without merging**
